### PR TITLE
Change 3th party to hash

### PR DESCRIPTION
**Pull request by AmonFla**

### CODE REVIEW

**Comment by AmonFla** [comment]
ok

**Comment by AmonFla** [comment]
ok

**Review by AmonFla — COMMENTED** [review]
ok

**Review by ghost — APPROVED** [review]
ok

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
todo ok

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
ok

**Pull request merged**
